apiVersion: v1
kind: Service
metadata:
  name: application-frontend-service
  labels:
    app: application-frontend-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.image.containerPort }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
  selector:
    app: application-frontend
