# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace:
  name: development


image:
  repository: vnethubcus.azurecr.io/application-frontend-dev:13463
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  containerPort: 4000


service:
  type: nodePort
  port: 80

ingress:
  path: /dev-fe

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
